"use client"

import { useForm } from "react-hook-form"
import { zodResolver } from "@hookform/resolvers/zod"
import * as z from "zod"
import { Button } from "@/components/ui/button"
import {
    Form,
    FormControl,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { createStudent, updateStudent } from "@/lib/api-users"
import { getClasses } from "@/lib/api-academic"
import { useToast } from "@/components/ui/use-toast"
import { useRef, useState, useEffect } from "react"
import { Loader2, Camera, Eye, Upload, UserPlus, X, Star, ShieldCheck } from "lucide-react"
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import { GuardianSelector } from "./guardian-selector"
import { Badge } from "@/components/ui/badge"

// Initial schema - will need to be expanded when backend supports more student-specific fields
const studentFormSchema = z.object({
    firstName: z.string().min(2, {
        message: "First name is required.",
    }),
    middleName: z.string().optional(),
    surname: z.string().min(2, {
        message: "Surname is required.",
    }),
    email: z.string().email({
        message: "Please enter a valid email address.",
    }),
    phone: z.string().optional(),
    // Temporary fields for UI demo purposes, as backend User model is simple
    admNo: z.string().optional(), // Auto-generated by backend now
    // className: z.string().min(1, { message: "Class is required" }), // Made optional for now
    className: z.string().optional(),
    // parentEmail: z.string().email().optional().or(z.literal('')), // Removed in favor of Guardians
    gender: z.enum(["Male", "Female"], {
        required_error: "Please select a gender.",
    }),
    dob: z.string().optional(),
    address: z.string().optional(),
})

type StudentFormValues = z.infer<typeof studentFormSchema>

interface StudentFormProps {
    onSuccess?: () => void
    initialData?: any // For editing
    studentId?: string // For editing
}

export function StudentForm({ onSuccess, initialData, studentId }: StudentFormProps) {
    const { toast } = useToast()
    const [isLoading, setIsLoading] = useState(false)
    const [classes, setClasses] = useState<any[]>([])
    const [selectedImage, setSelectedImage] = useState<File | null>(null)
    const [imagePreview, setImagePreview] = useState<string | null>(initialData?.profile_image || null)
    const [uploadError, setUploadError] = useState<string | null>(null)

    // Guardian State
    // We map initialData.guardians if available
    const [guardians, setGuardians] = useState<any[]>(initialData?.guardians || [])

    const fileInputRef = useRef<HTMLInputElement>(null)

    // Fetch classes on mount
    useEffect(() => {
        const fetchClasses = async () => {
            try {
                const data = await getClasses()
                setClasses(data)
            } catch (error) {
                console.error("Failed to fetch classes", error)
            }
        }
        fetchClasses()
    }, [])

    // Helper to split full name: Very basic splitting
    const splitName = (fullName: string) => {
        const parts = fullName.split(' ');
        if (parts.length === 1) return { firstName: parts[0], middleName: '', surname: '' };
        if (parts.length === 2) return { firstName: parts[0], middleName: '', surname: parts[1] };
        return {
            firstName: parts[0],
            middleName: parts.slice(1, -1).join(' '),
            surname: parts[parts.length - 1]
        };
    }

    const defaultValues = initialData ? {
        ...splitName(initialData.name),
        email: initialData.email,
        phone: initialData.phone || "",
        admNo: initialData.student?.admission_number || '',
        className: initialData.student?.class_id ? String(initialData.student.class_id) : "", // Placeholder mapping
        gender: initialData.student?.gender,
        dob: initialData.student?.dob || "",
        address: initialData.student?.address || "",
    } : {
        firstName: "",
        middleName: "",
        surname: "",
        email: "",
        phone: "",
        admNo: "",
        className: "",
        gender: undefined,
        dob: "",
        address: "",
    }

    const form = useForm<StudentFormValues>({
        resolver: zodResolver(studentFormSchema),
        defaultValues,
    })

    // Reset form if initialData changes (e.g. re-opening modal)
    useEffect(() => {
        if (initialData) {
            form.reset({
                ...splitName(initialData.name),
                email: initialData.email,
                phone: initialData.phone || "",
                admNo: initialData.student?.admission_number || '',
                className: initialData.student?.class_id ? String(initialData.student.class_id) : "",
                gender: initialData.student?.gender,
                dob: initialData.student?.dob || "",
                address: initialData.student?.address || "",
            })
            setGuardians(initialData.guardians || [])
        }
    }, [initialData, form])

    const handleAddGuardian = (guardian: any) => {
        // Check if already added
        if (guardians.some(g => g.id === guardian.id)) return

        // If first one, make primary
        const isFirst = guardians.length === 0
        setGuardians([...guardians, { ...guardian, is_primary: isFirst, relationship_type: 'Parent' }])
    }

    const handleRemoveGuardian = (id: number) => {
        setGuardians(guardians.filter(g => g.id !== id))
    }

    const handleSetPrimary = (id: number) => {
        setGuardians(guardians.map(g => ({
            ...g,
            is_primary: g.id === id
        })))
    }

    async function onSubmit(data: StudentFormValues) {
        setIsLoading(true)
        try {
            // Validate Guardians
            if (guardians.length === 0) {
                toast({
                    title: "Guardian Required",
                    description: "Please assign at least one guardian.",
                    variant: "destructive",
                })
                setIsLoading(false)
                return
            }

            // Transform to Student Payload
            // Note: We are now creating the full User + Student record
            const fullName = `${data.firstName} ${data.middleName ? data.middleName + ' ' : ''}${data.surname}`.trim();

            const formData = new FormData();
            formData.append('name', fullName);
            formData.append('email', data.email);
            if (data.phone) formData.append('phone', data.phone);
            // if (data.parentEmail) formData.append('parent_email', data.parentEmail); // Removed
            if (data.className) formData.append('class_id', data.className);
            formData.append('gender', data.gender);
            if (data.dob) formData.append('dob', data.dob);
            if (data.address) formData.append('address', data.address);

            // Append Guardians
            guardians.forEach((g, index) => {
                formData.append(`guardians[${index}][guardian_id]`, String(g.id || g.guardian_id)); // Handle both raw guardian or pivot structure
                formData.append(`guardians[${index}][relationship_type]`, g.relationship_type || 'Parent');
                formData.append(`guardians[${index}][is_primary]`, g.is_primary ? '1' : '0');
                if (g.is_primary) {
                    // Also set legacy parent_email field just in case backend uses it for notifications
                    formData.append('parent_email', g.email || '');
                }
            });

            if (selectedImage) {
                formData.append('profile_image', selectedImage);
            }

            if (studentId) {
                // UPDATE
                await updateStudent(studentId, formData)
                toast({
                    title: "Success",
                    description: "Student profile updated successfully.",
                })
            } else {
                // CREATE
                await createStudent(formData)
                toast({
                    title: "Success",
                    description: "Student account created successfully. Admission Number has been generated.",
                })
            }

            if (onSuccess) {
                onSuccess()
            }
        } catch (error: any) {
            console.error("Failed to save student", error)
            if (error.response && error.response.status === 422) {
                const errors = error.response.data.errors
                Object.keys(errors).forEach((key) => {
                    // Map backend errors to form fields
                    if (key === 'email') form.setError('email', { message: errors[key][0] })
                    else if (key === 'name') form.setError('firstName', { message: errors[key][0] }) // Generic name error to first name
                    else if (key === 'gender') form.setError('gender', { message: errors[key][0] })
                    else if (key === 'dob') form.setError('dob', { message: errors[key][0] })
                    else if (key === 'address') form.setError('address', { message: errors[key][0] })
                    else if (key.startsWith('guardians')) {
                        toast({
                            title: "Guardian Error",
                            description: errors[key][0],
                            variant: "destructive",
                        })
                    }
                    else if (key === 'profile_image') {
                        toast({
                            title: "Image Error",
                            description: errors[key][0],
                            variant: "destructive",
                        })
                    }
                })
                toast({
                    title: "Validation Error",
                    description: "Please check the form for errors.",
                    variant: "destructive",
                })
            } else {
                toast({
                    title: "Error",
                    description: "Failed to save student. Please try again.",
                    variant: "destructive",
                })
            }
        } finally {
            setIsLoading(false)
        }
    }

    return (
        <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">

                {/* Image Upload Section */}
                <div className="flex flex-col items-center gap-4 mb-6">
                    <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                            <div className="group relative h-28 w-28 rounded-full overflow-hidden border-4 border-background shadow-sm cursor-pointer hover:opacity-90 transition-opacity">
                                {imagePreview ? (
                                    <img src={imagePreview} alt="Preview" className="h-full w-full object-cover" />
                                ) : (
                                    <div className="h-full w-full bg-muted flex items-center justify-center text-muted-foreground">
                                        <Camera className="h-8 w-8 opacity-50" />
                                    </div>
                                )}
                                <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
                                    <Camera className="h-8 w-8 text-white" />
                                </div>
                            </div>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="center">
                            <DropdownMenuItem onClick={() => {
                                if (imagePreview) window.open(imagePreview, '_blank')
                            }}>
                                <Eye className="mr-2 h-4 w-4" />
                                View Current
                            </DropdownMenuItem>
                            <DropdownMenuItem onClick={() => fileInputRef.current?.click()}>
                                <Upload className="mr-2 h-4 w-4" />
                                Upload New
                            </DropdownMenuItem>
                        </DropdownMenuContent>
                    </DropdownMenu>

                    {/* Hidden Input */}
                    <Input
                        ref={fileInputRef}
                        type="file"
                        accept="image/*"
                        className="hidden"
                        onChange={(e) => {
                            const file = e.target.files?.[0]
                            if (file) {
                                // Basic size check (2MB) before state update
                                if (file.size > 2 * 1024 * 1024) {
                                    setUploadError("Image is too large (Max 2MB)")
                                    toast({
                                        title: "File too large",
                                        description: "Image must be less than 2MB",
                                        variant: "destructive"
                                    })
                                    e.target.value = '' // Reset input
                                    return
                                }
                                setUploadError(null)
                                setSelectedImage(file)
                                setImagePreview(URL.createObjectURL(file))
                            }
                        }}
                    />
                    <p className="text-sm text-muted-foreground">Click image to change. Max 2MB.</p>
                    {uploadError && <p className="text-sm text-destructive font-medium">{uploadError}</p>}
                </div>

                {/* Personal Details */}
                <div className="space-y-4 rounded-lg border p-4">
                    <h3 className="font-medium flex items-center gap-2">
                        <UserPlus className="h-4 w-4" />
                        Student Details
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                        <FormField
                            control={form.control}
                            name="firstName"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>First Name</FormLabel>
                                    <FormControl>
                                        <Input placeholder="Jane" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="middleName"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Middle Name</FormLabel>
                                    <FormControl>
                                        <Input placeholder="Middle" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="surname"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Surname</FormLabel>
                                    <FormControl>
                                        <Input placeholder="Doe" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <FormField
                            control={form.control}
                            name="gender"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Gender</FormLabel>
                                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                                        <FormControl>
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select Gender" />
                                            </SelectTrigger>
                                        </FormControl>
                                        <SelectContent>
                                            <SelectItem value="Male">Male</SelectItem>
                                            <SelectItem value="Female">Female</SelectItem>
                                        </SelectContent>
                                    </Select>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="dob"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Date of Birth (Optional)</FormLabel>
                                    <FormControl>
                                        <Input type="date" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                    </div>
                </div>

                {/* Academic & Contact */}
                <div className="space-y-4 rounded-lg border p-4 bg-muted/20">
                    <div className="grid grid-cols-2 gap-4">
                        {/* Admission Number is now System Generated, we can hide it or make it read-only for edit */}
                        {studentId && (
                            <FormField
                                control={form.control}
                                name="admNo"
                                render={({ field }) => (
                                    <FormItem>
                                        <FormLabel>Admission No</FormLabel>
                                        <FormControl>
                                            <Input {...field} disabled />
                                        </FormControl>
                                        <FormMessage />
                                    </FormItem>
                                )}
                            />
                        )}

                        <FormField
                            control={form.control}
                            name="className"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Class</FormLabel>
                                    <Select onValueChange={field.onChange} defaultValue={field.value}>
                                        <FormControl>
                                            <SelectTrigger>
                                                <SelectValue placeholder="Select Class" />
                                            </SelectTrigger>
                                        </FormControl>
                                        <SelectContent>
                                            {classes.length > 0 ? (
                                                classes.map((cls) => (
                                                    <SelectItem key={cls.id} value={String(cls.id)}>
                                                        {cls.name} {cls.stream ? `(${cls.stream})` : ''}
                                                    </SelectItem>
                                                ))
                                            ) : (
                                                <SelectItem value="none" disabled>No classes found</SelectItem>
                                            )}
                                        </SelectContent>
                                    </Select>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <FormField
                            control={form.control}
                            name="email"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Student Email (Login)</FormLabel>
                                    <FormControl>
                                        <Input placeholder="jane@school.com" type="email" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                    {studentId && <p className="text-xs text-muted-foreground">Changing email will change the user's login.</p>}
                                </FormItem>
                            )}
                        />
                        <FormField
                            control={form.control}
                            name="phone"
                            render={({ field }) => (
                                <FormItem>
                                    <FormLabel>Student Phone (Optional)</FormLabel>
                                    <FormControl>
                                        <Input placeholder="07xx xxx xxx" {...field} />
                                    </FormControl>
                                    <FormMessage />
                                </FormItem>
                            )}
                        />
                    </div>
                    <FormField
                        control={form.control}
                        name="address"
                        render={({ field }) => (
                            <FormItem>
                                <FormLabel>Address (Optional)</FormLabel>
                                <FormControl>
                                    <Input placeholder="Address" {...field} />
                                </FormControl>
                                <FormMessage />
                            </FormItem>
                        )}
                    />
                </div>

                {/* Guardians Section */}
                <div className="space-y-4 rounded-lg border p-4 bg-blue-50/50 border-blue-100">
                    <h3 className="font-medium flex items-center gap-2 text-blue-900">
                        <ShieldCheck className="h-4 w-4" />
                        Guardians (At least one required)
                    </h3>

                    <div className="space-y-3">
                        {guardians.map((guardian, index) => (
                            <div key={guardian.id || index} className="flex items-center justify-between p-3 bg-white rounded-md border shadow-sm">
                                <div>
                                    <div className="flex items-center gap-2">
                                        <p className="font-medium">{guardian.first_name} {guardian.last_name}</p>
                                        {guardian.is_primary && <Badge className="bg-blue-600 text-[10px] h-5">Primary</Badge>}
                                    </div>
                                    <p className="text-xs text-muted-foreground">{guardian.relationship_type || 'Parent'} • {guardian.phone_number}</p>
                                </div>
                                <div className="flex items-center gap-2">
                                    {!guardian.is_primary && (
                                        <Button
                                            size="sm"
                                            variant="ghost"
                                            type="button"
                                            className="text-xs h-7"
                                            onClick={() => handleSetPrimary(guardian.id)}
                                        >
                                            Make Primary
                                        </Button>
                                    )}
                                    <Button
                                        size="icon"
                                        variant="ghost"
                                        className="h-8 w-8 text-muted-foreground hover:text-destructive"
                                        type="button"
                                        onClick={() => handleRemoveGuardian(guardian.id)}
                                    >
                                        <X className="h-4 w-4" />
                                    </Button>
                                </div>
                            </div>
                        ))}

                        <div className="pt-2">
                            <GuardianSelector
                                onSelect={handleAddGuardian}
                                selectedGuardians={guardians}
                            />
                            <p className="text-xs text-muted-foreground mt-2">
                                * Primary guardian will receive all communications by default.
                            </p>
                        </div>
                    </div>
                </div>

                <div className="flex justify-end pt-4">
                    <Button type="submit" disabled={isLoading}>
                        {isLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        {studentId ? 'Update Student' : 'Create Student'}
                    </Button>
                </div>
            </form>
        </Form>
    )
}
