<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\SchoolClass;
use Illuminate\Http\Request;

class SchoolClassController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function __construct()
    {
        // "school_class" matches the route parameter name generated by apiResource for SchoolClass model
        $this->authorizeResource(SchoolClass::class, 'school_class');
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return SchoolClass::with(['currentTeacher.teacher'])->withCount('students')->get();
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'grade_level' => 'required|integer',
            'stream' => 'nullable|string|max:50',
            'curriculum' => 'required|in:CBC,8-4-4',
        ]);

        return SchoolClass::create($validated);
    }

    /**
     * Display the specified resource.
     */
    public function show($id)
    {
        $schoolClass = SchoolClass::findOrFail($id);
        return $schoolClass->load(['currentTeacher.teacher', 'students.user']);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, $id)
    {
        $schoolClass = SchoolClass::findOrFail($id);

        $validated = $request->validate([
            'name' => 'sometimes|required|string|max:255',
            'grade_level' => 'sometimes|required|integer',
            'stream' => 'nullable|string|max:50',
            'curriculum' => 'sometimes|required|in:CBC,8-4-4',
        ]);

        $schoolClass->update($validated);

        return $schoolClass;
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(SchoolClass $schoolClass)
    {
        $schoolClass->delete();

        return response()->noContent();
    }
}
